title: Vaibhav Singh # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description:  # your text below (remove <br> elements if you don't need line breaks)
  <b>Machine Learning Platforms</b>
  <br>
  <a href="https://github.com/ultrons">GitHub</a>   
  <a> | </a>
  <a href="https://ultrons.medium.com">Medium</a>   
  <a> | </a>
  <a href="https://www.linkedin.com/in/1vaibhavsingh/">LinkedIn</a>
  <a> | </a>
  <a href="https://twitter.com/u1trons">Twitter</a> 
  <br><br>
  <b>Current Focus Areas&#58; </b><br>
  &#8901; Machine Learning Accelerators <br>
  &#8901; Operationalization of Machine Models <br>
  <br>
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
